opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - empty_string
  - private_action
  - discouraged_object_literal
  - sorted_first_last
  - contains_over_first_not_nil
  - multiline_arguments

disabled_rules:
  - statement_position
type_body_length:
  warning: 200
  error: 400

private_outlet:
  allow_private_set: true

file_length:
  warning: 300
  error: 500

type_name:
  warning: 64
  error: 65

force_unwrapping:
  severity: error

function_body_length:
  warning: 20
  error: 40

implicitly_unwrapped_optional:
  mode: all
  severity: error

disabled_rules:
  - trailing_whitespace

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

statement_position:
  statement_mode: uncuddled_else

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - MarvelTests
  - MarvelUITests

